### ISSUE TITLE
S'assurer que la table `statistiques` possède les données nécessaires

### ISSUE THREAD

**Issue by Chat-mots** [Chat-mots/projet-terminale-nsi#11]
La bibliothèque python pour les requêtes est presque terminé et le fichier de création de la database aussi. Avant de terminer ça, vérifier que la table statistiques possèdent suffisamment de données intéressantes serait à faire.

@ritorizo @Minemew2 @ebrehin @Nbrehin pourriez vous jeter un oeil et me prévenir si vous souhaitez que plus d'informations soit stockés.
![image](https://user-images.githubusercontent.com/65656020/165075501-8117ce9b-8fab-4a63-aa3a-b14f7fb45313.png)

De mon point de vue, je ne vois pas quoi rajouter, une opinion extérieur verrait peut-être des choses.

**Comment by Chat-mots** [comment]
le temps de jeu est en **seconde**, pas en minute. Le nombre de morts est déjà compté

**Comment by Nbrehin** [comment]
Il faut aussi ajouter les données d'ELO. Pas seulement le plus haut score d'ELO atteint mais aussi celui actuel du joueur.

**Comment by Nbrehin** [comment]
oublie-ça
